name: 🚀 Deploy
on:
  push:
    branches:
      - main
  pull_request: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: write
  contents: read

jobs:

  test:
    name: 🧪 Test
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - name: 🏄 Copy test env vars
        run: cp .env.example .env

      - name: ⎔ Setup bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.2.4

      - name: 📥 Download deps
        run: bun install

      - name: 🧪 Test
        run: bun test

  deploy:
    name: 🚀 Deploy
    runs-on: ubuntu-latest
    needs: [test]
    # only build/deploy branches on pushes
    if: ${{ github.event_name == 'push' }}

    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - name: ⎔ Setup bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.2.4

      - name: 🚀 Deploy Production
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
